# Arrays vs Lists

In [1]:
list_two = list(range(1,4))
list_three = list(range(1,4))
list_sum = []

for index in range(3):
    list_two[index] = list_two[index] ** 2
    list_three[index] = list_three[index] ** 3
    list_sum.append(list_two[index] + list_three[index])
    
print(list_sum)

[2, 12, 36]


In [2]:
import numpy as np

In [3]:
array_two = np.arange(1,4) ** 2
array_three = np.arange(1,4) ** 3
print(array_two + array_three)

[ 2 12 36]


In [4]:
print(np.power(np.array([1,2,3]), 4))

[ 1 16 81]


In [5]:
print(np.negative(np.array([1,2,3])))

[-1 -2 -3]


In [6]:
sample_array = np.array([1,2,3])

print(np.exp(sample_array))
print(np.log(sample_array))
print(np.sin(sample_array))

[ 2.71828183  7.3890561  20.08553692]
[0.         0.69314718 1.09861229]
[0.84147098 0.90929743 0.14112001]


# Multi Dimensional Array

In [17]:
x = np.arange(3)
y = np.arange(3, 6)
z = np.arange(6, 9)

multi_array = np.array([x,y,z], dtype = np.float)
print(multi_array)
print(multi_array.shape)
print(multi_array.dtype)
print(multi_array[1,2])

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
(3, 3)
float64
5.0


In [9]:
#evenly spaced
w = np.linspace(1, 10, 50)
print(w)

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


In [12]:
b = np.linspace(1, 30, 3, True)
b

array([ 1. , 15.5, 30. ])

In [13]:
c = np.linspace(1, 30, 3, False)
c

array([ 1.        , 10.66666667, 20.33333333])

# 1D Slicing

In [19]:
x = np.arange(1, 10)
print(x)

[1 2 3 4 5 6 7 8 9]


In [23]:
# slice the array
print(x[2:])
print(x[:7])
print(x[2:7])
print(x[2:7:2])

[3 4 5 6 7 8 9]
[1 2 3 4 5 6 7]
[3 4 5 6 7]
[3 5 7]


# Reshape

In [24]:
x = np.arange(9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [25]:
y = np.arange(9).reshape(3,5)
print(y)

ValueError: cannot reshape array of size 9 into shape (3,5)

In [31]:
z = np.arange(9).reshape(3, -1)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [34]:
a = np.arange(18).reshape(2,3,3)
print(a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]


# n-Dimensional Slicing

In [37]:
a = np.arange(18).reshape(3,2,3)
print(a)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]


In [38]:
#get 10
a[1,1,1]

10

In [54]:
#get 6,7,8,9,10,11
a[1,:2,:3]
a[1,:,:]
a[1,...]

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [59]:
#:end:step
a[1, :2, :3:2]

array([[ 6,  8],
       [ 9, 11]])

In [62]:
comparison_operation = a > 5
print(comparison_operation)
print(a[comparison_operation])

[[[False False False]
  [False False False]]

 [[ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]]]
[ 6  7  8  9 10 11 12 13 14 15 16 17]


In [63]:
a.max()

17

In [64]:
a.min()

0

# Manipulate Array Shape

In [66]:
x = np.arange(9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [67]:
# flattened array -> mutate original value
ravelled_array = x.ravel()
print(ravelled_array)

[0 1 2 3 4 5 6 7 8]


In [68]:
# flattened array -> make a copy of original value
flattened_array = x.flatten()
print(flattened_array)

[0 1 2 3 4 5 6 7 8]


In [69]:
y = np.arange(9)
y.shape = [3, 3]
print(y)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [72]:
#transpose
print(y.transpose())
print('--- same result ---')
print(y.T)

[[0 3 6]
 [1 4 7]
 [2 5 8]]
--- same result ---
[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [75]:
# resize -> repeated to filled in the prompted size
print(np.resize(y, (6,6)))

[[0 1 2 3 4 5]
 [6 7 8 0 1 2]
 [3 4 5 6 7 8]
 [0 1 2 3 4 5]
 [6 7 8 0 1 2]
 [3 4 5 6 7 8]]


In [77]:
# np.zeros return float by default
print(np.zeros((6,6), dtype=int))

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [78]:
# np.ones return float by default
print(np.ones((6,6), dtype=int))

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]


In [80]:
# identity matrix. eye = I. Mind blown!
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [81]:
# random with normal distribution value
np.random.rand(4,4)

array([[0.06438932, 0.73415942, 0.02361561, 0.20656287],
       [0.08397259, 0.16074244, 0.99221374, 0.15220821],
       [0.46858422, 0.28444188, 0.83892224, 0.07606435],
       [0.76332602, 0.0754226 , 0.96254232, 0.37535959]])

# Matrix Multiplication

In [82]:
mat_a = np.matrix([0,3,5,5,5,2]).reshape(2,3)
mat_a

matrix([[0, 3, 5],
        [5, 5, 2]])

In [84]:
mat_b = np.matrix([3,4,3,-2,4,-2]).reshape(3,2)
mat_b

matrix([[ 3,  4],
        [ 3, -2],
        [ 4, -2]])

In [85]:
mat_a * mat_b

matrix([[ 29, -16],
        [ 38,   6]])

In [87]:
product = np.matmul(mat_a, mat_b)
product

matrix([[ 29, -16],
        [ 38,   6]])

In [88]:
mat_a @ mat_b

matrix([[ 29, -16],
        [ 38,   6]])

# Stacking

In [93]:
x = np.arange(4).reshape(2,2)
print(x)
print(x.shape)

[[0 1]
 [2 3]]
(2, 2)


In [94]:
y = np.arange(4,8).reshape(2,2)
print(y)
print(y.shape)

[[4 5]
 [6 7]]
(2, 2)


In [109]:
#horizontal stacking
z1 = np.hstack((x,y))
print(z1)
print(z1.shape)

[[0 1 4 5]
 [2 3 6 7]]
(2, 4)


In [110]:
# ALTERNATIVE (h-stacking)
w1 = np.concatenate((x,y), axis=1)
print(w1)

[[0 1 4 5]
 [2 3 6 7]]


In [111]:
print(w1 == z1)

[[ True  True  True  True]
 [ True  True  True  True]]


In [125]:
# column stacking = ALTERNATIVE hstack
print(np.column_stack((x, y)) == np.hstack((x, y)))

[[ True  True  True  True]
 [ True  True  True  True]]


In [112]:
#vertical stacking
z2 = np.vstack((x,y))
print(z2)
print(z2.shape)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
(4, 2)


In [113]:
# ALTERNATIVE (v-stacking)
w2 = np.concatenate((x,y), axis=0)
print(w2)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [114]:
print(w2 == z2)

[[ True  True]
 [ True  True]
 [ True  True]
 [ True  True]]


In [126]:
# row stacking = ALTERNATIVE vstack
print(np.row_stack((x,y)) == np.vstack((x,y)))

[[ True  True]
 [ True  True]
 [ True  True]
 [ True  True]]


In [121]:
print(x)
print(x.shape)

[[0 1]
 [2 3]]
(2, 2)


In [120]:
y = x * 2
print(y)
print(y.shape)

[[0 2]
 [4 6]]
(2, 2)


In [122]:
# x(2,2,1) + y(2,2,1) = (2,2,2)
depth_stack = np.dstack([x, y])
print(depth_stack)
print(depth_stack.shape)

[[[0 0]
  [1 2]]

 [[2 4]
  [3 6]]]
(2, 2, 2)
